### PR TITLE
Change UI to display 3 sections

### LINKED ISSUE #78: As a user, I would like to see client list and session list
so that I can arrange client's session at a glance.

### PR DESCRIPTION
**Pull request by tanweijie123**

### CODE REVIEW

**Comment by tanweijie123** [comment]
fixes #78

**Review by kelvinvin — APPROVED** [review]
Right sidebar previously had a scrollbar that doesn't show now, but I think it's fine not to have it. Lgtm!

**Comment by tanweijie123** [comment]
> Right sidebar previously had a scrollbar that doesn't show now, but I think it's fine not to have it. Lgtm!

Vbox have auto hide scrollbar if not necessary. So maybe your screen size bigger? 
image

**Comment by kelvinvin** [comment]
> > Right sidebar previously had a scrollbar that doesn't show now, but I think it's fine not to have it. Lgtm!
> 
> Vbox have auto hide scrollbar if not necessary. So maybe your screen size bigger?
> image

Oh I think its just my screen then. Can merge

**Pull request merged**
